### ISSUE TITLE
Xcode warnings: Dsymutil warning: unable to open object file

### ISSUE THREAD

**Issue by chrismear** [chrismear/renios#66]
Lots of these; one example:

```
warning: (armv7) /Users/chrismear/Development/Projects/renios/renios/dependencies/tmp/pygame-1.9.1release/build/temp.macosx-10.8-x86_64-2.7/src/base.o unable to open object file
```

This started happening when we began building multiple builds (multiple architectures + debug/release versions). I'm guessing it's because we don't keep the intermediate build results around on disk, instead wiping the tmp directory for each new build.

**Comment by chrismear** [comment]
Also, these aren't currently present at all in the binary distribution, even if this gets fixed on the development machine (as noted in #69). Need to work out how to package the libraries properly so that this debugging symbols warning doesn't happen even if you only have the .a files -- is this even possible?

**Comment by brocococonut** [comment]
Another problem with it is that it's looking in a user directory that isn't present on others machines. The username "chrismear" is only present on your computer.

**Comment by chrismear** [comment]
Yeah, it seems like the default behaviour of the linker is to leave those path references in when it builds the .a files. I think simply stripping the debug symbols from the library binaries would get rid of the warnings, but ideally I'd like to do that in a way that lets us resymbolicate crash logs when necessary.

**Comment by chrismear** [comment]
This answer suggests, as I suspected, that producing a dSYM file for static libraries is pointless: http://stackoverflow.com/a/13720063/6471

So probably just stripping symbols for the binary distribution is the way to go. If developers need to debug, they can always build from source.

**Comment by brocococonut** [comment]
There's an issue with building from the source though. I've tested it on a
completely fresh install of Mac OS x (with the dependencies you listed in
the documentation +xcode and Xcode command line tools) and it won't build.
I'll give you an error report in a moment. Remember that it's on a fresh
install of the operating system.

**Comment by brocococonut** [comment]
It's in the way you compile the Python source. It never gets past that stage. Where would you like me to attach the full build log?

**Comment by chrismear** [comment]
Could you put the log into a Gist: https://gist.github.com/ and then link to it from a new ticket please? Thanks very much!

**Comment by brocococonut** [comment]
https://gist.github.com/HtTYDDS/c0b6f9448743c4650988
There you go.

**Comment by brocococonut** [comment]
I'm curious as to why it builds correctly on your machine and not mine seeing as we're building from the same source..

**Comment by chrismear** [comment]
Yup, I'm curious too! I'll try on a fresh OS X install and see if I can reproduce it.

**Comment by brocococonut** [comment]
Cool. Yeah, the only modified thing about this install is the installation of the (4 I think it was?) pre-requisites to compile the source.
