### ISSUE TITLE
Static libs couldn't be used on iOS simulator

### ISSUE THREAD

**Issue by mdifferent** [chrismear/renios#67]
Static libraries provided by renios is compiled for armv7 (lipo -info XXX.a), which couldn't be used when deployed on simulator, because the simulator on Mac is x86 architecture. I got this error:

ld: warning: ignoring file /Users/whm/Downloads/renios-0.2/dependencies/build/lib/libavcodecnoinverse.a, file was built for archive which is not the architecture being linked (i386): /Users/whm/Downloads/renios-0.2/dependencies/build/lib/libavcodecnoinverse.a
(...and other libraries)

Undefined symbols for architecture i386:
  "_PyEval_InitThreads", referenced from:
      _SDL_main in main.o
  "_PyRun_SimpleFileExFlags", referenced from:
      _SDL_main in main.o
  "_PySys_SetArgv", referenced from:
      _SDL_main in main.o
  "_Py_Finalize", referenced from:
      _SDL_main in main.o
  "_Py_Initialize", referenced from:
      _SDL_main in main.o
  "_Py_SetProgramName", referenced from:
      _SDL_main in main.o
  "_Py_SetPythonHome", referenced from:
      _SDL_main in main.o
  "_main", referenced from:
      start in crt1.o
     (maybe you meant: _SDL_main)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

May be you need to build these libraries for both simulator and real device separately.

**Comment by chrismear** [comment]
Thank you for the feedback! The latest code on the 'master' branch does in fact build for both the arm and simulator architectures, and produces a fat binary that runs on both (see this issue for more details: https://github.com/chrismear/renios/issues/1). But I don't think I have packaged a release since then, so if you're using the latest release download you will probably still have this problem.

I'll try and cut a new release soon that includes simulator support. In the meantime, I'll close this ticket, but if you try a build from the latest 'master' and it still doesn't work then please reopen this, as that is definitely a bug!

**Comment by mdifferent** [comment]
I have tried to build master branch but failed during that, I think they couldn't find "i686-apple-darwin11-llvm-gcc-4.2", there is not such file in "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/". The I dev on Mac OS X 10.9 + Xcode 5.0. Log finally print:

Building for iOS
patching file configure
patching file Makefile.pre.in
patching file setup.py
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't open input file: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator7.0.sdk/usr/lib/libgcc_s.1.dylib (No such file or directory)
configure: WARNING: if you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used
checking for --enable-universalsdk... no
checking for --with-universal-archs... 32-bit
checking MACHDEP... darwin
checking EXTRAPLATDIR... $(PLATMACDIRS)
checking machine type as reported by uname -m... x86_64
checking for --without-gcc... no
checking for i686-apple-darwin-gcc... /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/i686-apple-darwin11-llvm-gcc-4.2
checking whether the C compiler works... no
configure: error: in `/Users/whm/Downloads/renios-master/dependencies/tmp/Python-2.7.3':
configure: error: C compiler cannot create executables

**Comment by chrismear** [comment]
Hmm, looks like we need to update the compiler path. Thanks for the log details. I've made a new ticket to track this bug here: #68

**Comment by chrismear** [comment]
@mdifferent I've just made a new release, 0.3, that includes the binaries for the simulator: https://github.com/chrismear/renios/releases/tag/v0.3

Also, the current master branch should now be building cleanly on Xcode 5, if you'd prefer to build from source.
