### ISSUE TITLE
Set up continuous integration

### ISSUE THREAD

**Issue by chrismear** [chrismear/renios#72]
Should test full build from source based on `master` branch, and building a project from the binary distribution.

**Comment by brocococonut** [comment]
Build still fails with Python
https://gist.github.com/HtTYDDS/310ff6f64479f911d1b5#file-gistfile1-txt

**Comment by chrismear** [comment]
Yup, please follow that issue on ticket number #71. This ticket is for setting up CI.

**Comment by chrismear** [comment]
Travis setup is now done to the point where the build starts, but since a full build takes over an hour and the Travis timeout is 50 minutes we never complete.

Since the only target we can do a final app build for on Travis is iphonesimulator, we could do a build of just this platform, which should bring it under the time limit. Not sure if this is really useful or not. It would catch some silly errors in the overall build process, but would give a misleading 'passed' result if errors in the cross-compilation were introduced, which really is the most important part of the project.

Alternative is just to have a local VM to run occasional builds on manually.
